[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "cross-site"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Disposition = "attachment; filename=portfolio.wasm"

[[headers]]
  for = "/assets/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Disposition = "attachment; filename=portfolio.wasm"
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"