[build]
  base = "web"
  command = "pnpm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Disposition = "attachment; filename=portfolio.wasm"

[[headers]]
  for = "/assets/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Content-Disposition = "attachment; filename=portfolio.wasm"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cross-Origin-Embedder-Policy = "cross-site"
    Content-Security-Policy = "frame-ancestors https://widgets.commoninja.com"